export const ADD_THREE_CARDS = "ADD_THREE_CARDS";
export const RESET = "RESET";
export const USER_SELECT_CARDS = "USER_SELECT_CARDS";
export const REPLACE_SET_CARD = "REPLACE_SET_CARD";
export const SELECT_CARD_BE_ZERO = "SELECT_CARD_BE_ZERO";
export const CHANGE_DIFFICULTY = "CHANGE_DIFFICULTY";
